# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5989d61afdfbd537ba12b8574fbbc8d7cb0ffd28d8c2c216700f247fd5d921f1c0d0d4856176eb3bc306d63026ce04058ad920a6a4f7c525cc039e25e55fe91d

test:
  secret_key_base: 116e770de060d9bc0fdd547dcdf57013ee2950791632db057c25230a0b8563b4c4a6263e60bd50e66e24f10a75ca48fb8a2fdaad0cf0b1aacf3f04abb94a09c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
